FROM debian:stable-slim

# Evita perguntas interativas durante a instalação de pacotes
ENV DEBIAN_FRONTEND=noninteractive

# Instala o compilador Free Pascal (FPC) e ferramentas de teste
RUN apt-get update && apt-get install -y \
    fpc \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

# Copia os fontes do projeto (Horse) e os exemplos
COPY . .

# Compila o exemplo Lazarus/FPC via linha de comando
RUN fpc -Mdelphi -O3 -dHORSE_PROVIDER_EPOLL -Fusrc samples/lazarus/epoll/EpollConsole.lpr -oEpollConsole && mv samples/lazarus/epoll/EpollConsole .

# Expõe a porta padrão do exemplo Epoll
EXPOSE 9095

# Inicia o servidor
CMD ["./EpollConsole"]
