{***************************************************************************}
{                                                                           }
{           Generated by horse-pb-compiler                                  }
{                                                                           }
{***************************************************************************}
unit users;

{$IFDEF FPC}
  {$MODE DELPHI}{$H+}
  {$M+}
{$ENDIF}

interface

uses
  System.Classes,
  System.SysUtils,
  Horse.Grpc.Attributes;

type
  TUserRequest = class;
  TUserResponse = class;

  [GrpcMessage]
  TUserRequest = class
  private
    Fid: Integer;
  {$IFNDEF FPC}
  public
    [ProtoMember(1)]
    property id: Integer read Fid write Fid;
  {$ELSE}
  published
    [ProtoMember(1)]
    property id: Integer read Fid write Fid;
  {$ENDIF}
  public
    procedure Serialize(AStream: TStream);
    procedure Deserialize(AStream: TStream);
  end;

  [GrpcMessage]
  TUserResponse = class
  private
    Fid: Integer;
    Fname: string;
    Femail: string;
  {$IFNDEF FPC}
  public
    [ProtoMember(1)]
    property id: Integer read Fid write Fid;
    [ProtoMember(2)]
    property name: string read Fname write Fname;
    [ProtoMember(3)]
    property email: string read Femail write Femail;
  {$ELSE}
  published
    [ProtoMember(1)]
    property id: Integer read Fid write Fid;
    [ProtoMember(2)]
    property name: string read Fname write Fname;
    [ProtoMember(3)]
    property email: string read Femail write Femail;
  {$ENDIF}
  public
    procedure Serialize(AStream: TStream);
    procedure Deserialize(AStream: TStream);
  end;

  [GrpcService('users.UserService')]
  IUserService = interface(IInvokable)
    ['{DFB2844E-D44A-4721-9F06-1F73851FC1B5}']
    [GrpcMethod('GetUser')]
    function GetUser(const ARequest: TUserRequest): TUserResponse;
  end;

implementation

uses
  Horse.Core.Protobuf.Serializer;

procedure TUserRequest.Serialize(AStream: TStream);
var
  LWriter: TProtobufWriter;
begin
  LWriter := TProtobufWriter.Create(AStream);
  try
    LWriter.WriteInt32(1, Fid);
  finally
    LWriter.Free;
  end;
end;

procedure TUserRequest.Deserialize(AStream: TStream);
var
  LReader: TProtobufReader;
begin
  LReader := TProtobufReader.Create(AStream);
  try
    while LReader.ReadField do
    begin
      case LReader.Tag of
        1:
          begin
            Fid := LReader.ReadInt32;
          end;
      else
        LReader.SkipField;
      end;
    end;
  finally
    LReader.Free;
  end;
end;

procedure TUserResponse.Serialize(AStream: TStream);
var
  LWriter: TProtobufWriter;
begin
  LWriter := TProtobufWriter.Create(AStream);
  try
    LWriter.WriteInt32(1, Fid);
    LWriter.WriteString(2, Fname);
    LWriter.WriteString(3, Femail);
  finally
    LWriter.Free;
  end;
end;

procedure TUserResponse.Deserialize(AStream: TStream);
var
  LReader: TProtobufReader;
begin
  LReader := TProtobufReader.Create(AStream);
  try
    while LReader.ReadField do
    begin
      case LReader.Tag of
        1:
          begin
            Fid := LReader.ReadInt32;
          end;
        2:
          begin
            Fname := LReader.ReadString;
          end;
        3:
          begin
            Femail := LReader.ReadString;
          end;
      else
        LReader.SkipField;
      end;
    end;
  finally
    LReader.Free;
  end;
end;

end.
