unit Horse.Protobuf.Compiler.Engine;

interface

uses
  System.SysUtils,
  System.Classes,
  System.Generics.Collections;

type
  TProtoField = record
    ProtoType: string;
    DelphiType: string;
    Name: string;
    Tag: Integer;
  end;

  TProtoMessage = class
    Name: string;
    Fields: TList<TProtoField>;
    constructor Create;
    destructor Destroy; override;
  end;

  TProtoMethod = record
    Name: string;
    RequestType: string;
    ResponseType: string;
  end;

  TProtoService = class
    Name: string;
    Methods: TList<TProtoMethod>;
    constructor Create;
    destructor Destroy; override;
  end;

procedure CompileProto(const InputFile, OutputFile: string);

implementation

{ TProtoMessage }

constructor TProtoMessage.Create;
begin
  Fields := TList<TProtoField>.Create;
end;

destructor TProtoMessage.Destroy;
begin
  Fields.Free;
  inherited;
end;

{ TProtoService }

constructor TProtoService.Create;
begin
  Methods := TList<TProtoMethod>.Create;
end;

destructor TProtoService.Destroy;
begin
  Methods.Free;
  inherited;
end;

{ Helper Functions }

function MapType(const ProtoType: string): string;
begin
  if ProtoType = 'string' then Result := 'string'
  else if ProtoType = 'int32' then Result := 'Integer'
  else if ProtoType = 'int64' then Result := 'Int64'
  else if ProtoType = 'bool' then Result := 'Boolean'
  else if ProtoType = 'double' then Result := 'Double'
  else if ProtoType = 'float' then Result := 'Single'
  else if ProtoType = 'bytes' then Result := 'TBytes'
  else Result := 'T' + ProtoType;
end;

function CleanToken(const Token: string): string;
begin
  Result := Token.Replace(';', '').Replace('{', '').Replace('}', '').Trim;
end;

procedure CompileProto(const InputFile, OutputFile: string);
var
  Input: TStringList;
  Output: TStringList;
  Package: string;
  Messages: TObjectList<TProtoMessage>;
  Services: TObjectList<TProtoService>;
  CurrentMsg: TProtoMessage;
  CurrentSvc: TProtoService;
  i: Integer;
  Line: string;
  Tokens: TArray<string>;
  Fld: TProtoField;
  Mtd: TProtoMethod;
  UnitName: string;
  Msg: TProtoMessage;
  Svc: TProtoService;
  GuidStr: string;
begin
  Input := TStringList.Create;
  Output := TStringList.Create;
  Messages := TObjectList<TProtoMessage>.Create(True);
  Services := TObjectList<TProtoService>.Create(True);
  try
    Input.LoadFromFile(InputFile);
    Package := '';
    CurrentMsg := nil;
    CurrentSvc := nil;
 
    for i := 0 to Input.Count - 1 do
    begin
      Line := Input[i].Trim;
      if Line.StartsWith('//') or (Line = '') then
        Continue;
 
      Tokens := Line.Split([' ', #9, '=', ';', '(', ')'],
        TStringSplitOptions.ExcludeEmpty);
      if Length(Tokens) = 0 then Continue;
 
      if Tokens[0] = 'package' then
      begin
        Package := CleanToken(Tokens[1]);
      end
      else if Tokens[0] = 'message' then
      begin
        CurrentMsg := TProtoMessage.Create;
        CurrentMsg.Name := CleanToken(Tokens[1]);
        Messages.Add(CurrentMsg);
      end
      else if Tokens[0] = 'service' then
      begin
        CurrentSvc := TProtoService.Create;
        CurrentSvc.Name := CleanToken(Tokens[1]);
        Services.Add(CurrentSvc);
      end
      else if Line.StartsWith('}') then
      begin
        CurrentMsg := nil;
        CurrentSvc := nil;
      end
      else if Assigned(CurrentMsg) then
      begin
        if Length(Tokens) >= 3 then
        begin
          Fld.ProtoType := Tokens[0];
          Fld.DelphiType := MapType(Fld.ProtoType);
          Fld.Name := Tokens[1];
          Fld.Tag := StrToIntDef(Tokens[2], 0);
          CurrentMsg.Fields.Add(Fld);
        end;
      end
      else if Assigned(CurrentSvc) and (Tokens[0] = 'rpc') then
      begin
        if Length(Tokens) >= 5 then
        begin
          Mtd.Name := Tokens[1];
          Mtd.RequestType := Tokens[2];
          Mtd.ResponseType := Tokens[4];
          CurrentSvc.Methods.Add(Mtd);
        end;
      end;
    end;
 
    UnitName := ChangeFileExt(ExtractFileName(OutputFile), '');
    Output.Add('{***************************************************************************}');
    Output.Add('{                                                                           }');
    Output.Add('{           Generated by horse-pb-compiler                                  }');
    Output.Add('{                                                                           }');
    Output.Add('{***************************************************************************}');
    Output.Add('unit ' + UnitName + ';');
    Output.Add('');
    Output.Add('{$IFDEF FPC}');
    Output.Add('  {$MODE DELPHI}{$H+}');
    Output.Add('  {$M+}');
    Output.Add('{$ENDIF}');
    Output.Add('');
    Output.Add('interface');
    Output.Add('');
    Output.Add('uses');
    Output.Add('  System.Classes,');
    Output.Add('  System.SysUtils,');
    Output.Add('  Horse.Grpc.Attributes;');
    Output.Add('');
    Output.Add('type');
 
    for Msg in Messages do
    begin
      Output.Add('  T' + Msg.Name + ' = class;');
    end;
    Output.Add('');
 
    for Msg in Messages do
    begin
      Output.Add('  [GrpcMessage]');
      Output.Add('  T' + Msg.Name + ' = class');
      Output.Add('  private');
      for Fld in Msg.Fields do
      begin
        Output.Add('    F' + Fld.Name + ': ' + Fld.DelphiType + ';');
      end;
      Output.Add('  {$IFNDEF FPC}');
      Output.Add('  public');
      for Fld in Msg.Fields do
      begin
        Output.Add('    [ProtoMember(' + IntToStr(Fld.Tag) + ')]');
        Output.Add('    property ' + Fld.Name + ': ' + Fld.DelphiType + ' read F' + Fld.Name + ' write F' + Fld.Name + ';');
      end;
      Output.Add('  {$ELSE}');
      Output.Add('  published');
      for Fld in Msg.Fields do
      begin
        Output.Add('    [ProtoMember(' + IntToStr(Fld.Tag) + ')]');
        Output.Add('    property ' + Fld.Name + ': ' + Fld.DelphiType + ' read F' + Fld.Name + ' write F' + Fld.Name + ';');
      end;
      Output.Add('  {$ENDIF}');
      Output.Add('  public');
      Output.Add('    procedure Serialize(AStream: TStream);');
      Output.Add('    procedure Deserialize(AStream: TStream);');
      Output.Add('  end;');
      Output.Add('');
    end;
 
    for Svc in Services do
    begin
      if Package <> '' then
        Output.Add('  [GrpcService(''' + Package + '.' + Svc.Name + ''')]')
      else
        Output.Add('  [GrpcService(''' + Svc.Name + ''')]');
      Output.Add('  I' + Svc.Name + ' = interface(IInvokable)');
      
      GuidStr := TGUID.NewGuid.ToString.Replace('{','').Replace('}','');
      Output.Add('    [''{' + GuidStr + '}'']');
      
      for Mtd in Svc.Methods do
      begin
        Output.Add('    [GrpcMethod(''' + Mtd.Name + ''')]');
        Output.Add('    function ' + Mtd.Name + '(const ARequest: T' + Mtd.RequestType + '): T' + Mtd.ResponseType + ';');
      end;
      Output.Add('  end;');
      Output.Add('');
    end;
 
    Output.Add('implementation');
    Output.Add('');
    Output.Add('uses');
    Output.Add('  Horse.Core.Protobuf.Serializer;');
    Output.Add('');
    for Msg in Messages do
    begin
      Output.Add('procedure T' + Msg.Name + '.Serialize(AStream: TStream);');
      Output.Add('var');
      Output.Add('  LWriter: TProtobufWriter;');
      Output.Add('begin');
      Output.Add('  LWriter := TProtobufWriter.Create(AStream);');
      Output.Add('  try');
      for Fld in Msg.Fields do
      begin
        if Fld.DelphiType = 'Integer' then
          Output.Add('    LWriter.WriteInt32(' + IntToStr(Fld.Tag) + ', F' + Fld.Name + ');')
        else if Fld.DelphiType = 'Int64' then
          Output.Add('    LWriter.WriteInt64(' + IntToStr(Fld.Tag) + ', F' + Fld.Name + ');')
        else if Fld.DelphiType = 'Double' then
          Output.Add('    LWriter.WriteDouble(' + IntToStr(Fld.Tag) + ', F' + Fld.Name + ');')
        else if Fld.DelphiType = 'Single' then
          Output.Add('    LWriter.WriteSingle(' + IntToStr(Fld.Tag) + ', F' + Fld.Name + ');')
        else if Fld.DelphiType = 'string' then
          Output.Add('    LWriter.WriteString(' + IntToStr(Fld.Tag) + ', F' + Fld.Name + ');')
        else if Fld.DelphiType = 'Boolean' then
          Output.Add('    LWriter.WriteBool(' + IntToStr(Fld.Tag) + ', F' + Fld.Name + ');')
        else if Fld.DelphiType = 'TBytes' then
          Output.Add('    LWriter.WriteBytes(' + IntToStr(Fld.Tag) + ', F' + Fld.Name + ');')
        else
        begin
          Output.Add('    if Assigned(F' + Fld.Name + ') then');
          Output.Add('      LWriter.WriteMessage(' + IntToStr(Fld.Tag) + ', THorseProtobufSerializer.Serialize(F' + Fld.Name + '));');
        end;
      end;
      Output.Add('  finally');
      Output.Add('    LWriter.Free;');
      Output.Add('  end;');
      Output.Add('end;');
      Output.Add('');

      Output.Add('procedure T' + Msg.Name + '.Deserialize(AStream: TStream);');
      Output.Add('var');
      Output.Add('  LReader: TProtobufReader;');
      Output.Add('begin');
      Output.Add('  LReader := TProtobufReader.Create(AStream);');
      Output.Add('  try');
      Output.Add('    while LReader.ReadField do');
      Output.Add('    begin');
      Output.Add('      case LReader.Tag of');
      for Fld in Msg.Fields do
      begin
        Output.Add('        ' + IntToStr(Fld.Tag) + ':');
        Output.Add('          begin');
        if Fld.DelphiType = 'Integer' then
          Output.Add('            F' + Fld.Name + ' := LReader.ReadInt32;')
        else if Fld.DelphiType = 'Int64' then
          Output.Add('            F' + Fld.Name + ' := LReader.ReadInt64;')
        else if Fld.DelphiType = 'Double' then
          Output.Add('            F' + Fld.Name + ' := LReader.ReadDouble;')
        else if Fld.DelphiType = 'Single' then
          Output.Add('            F' + Fld.Name + ' := LReader.ReadSingle;')
        else if Fld.DelphiType = 'string' then
          Output.Add('            F' + Fld.Name + ' := LReader.ReadString;')
        else if Fld.DelphiType = 'Boolean' then
          Output.Add('            F' + Fld.Name + ' := LReader.ReadBool;')
        else if Fld.DelphiType = 'TBytes' then
          Output.Add('            F' + Fld.Name + ' := LReader.ReadBytes;')
        else
        begin
          Output.Add('            if not Assigned(F' + Fld.Name + ') then');
          Output.Add('              F' + Fld.Name + ' := ' + Fld.DelphiType + '.Create;');
          Output.Add('            THorseProtobufSerializer.Deserialize(LReader.ReadBytes, F' + Fld.Name + ');');
        end;
        Output.Add('          end;');
      end;
      Output.Add('      else');
      Output.Add('        LReader.SkipField;');
      Output.Add('      end;');
      Output.Add('    end;');
      Output.Add('  finally');
      Output.Add('    LReader.Free;');
      Output.Add('  end;');
      Output.Add('end;');
      Output.Add('');
    end;
    Output.Add('end.');
 
    Output.SaveToFile(OutputFile);
  finally
    Input.Free;
    Output.Free;
    Messages.Free;
    Services.Free;
  end;
end;

end.
